
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
pool: Elanthamilan

resources:
  webhooks:
    - webhook: azdevops          ### Webhook alias
      connection: azdevops

steps:
- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      import json
      json_string = json.dumps(${{ convertToJson(parameters.azdevops) }})
      print(json_string)
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'keyvault-fl'
    ScriptType: 'InlineScript'
    Inline: |
     
    azurePowerShellVersion: 'LatestVersion'
    


