
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
pool: Elanthamilan

resources:
  webhooks:
    - webhook: azdevops          ### Webhook alias
      connection: azdevops

steps:

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'keyvault-fl'
    ScriptType: 'InlineScript'
    Inline: |
     $jsonAlert =  "${{ parameters.azdevops.data.essentials.alertTargetIDs[0] }}"
     $pattern = "/subscriptions/[^/]+/resourcegroups/([^/]+)/providers/microsoft.compute/virtualmachines/([^/]+)"
     if ($jsonAlert -match $pattern) {
     $resourceGroupName = $matches[1]
     $vmName = $matches[2]
     Write-Host "Resource Group Name: $resourceGroupName"
     Write-Host "VM Name: $vmName"
     }
     else {
     Write-Host "No match found in the input string."
     }
     
    azurePowerShellVersion: 'LatestVersion'
    


